SET PATH=C:\Program Files\Keil\ARM\BIN40\;C:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\bin;C:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\lib;C:\MentorGraphics\9.5PADS\MGC_HOME.ixn\bin;C:\MentorGraphics\9.5PADS\MGC_HOME.ixn\lib;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
SET ARMCC41INC=C:\Program Files\Keil\ARM\RV31\INC
SET ARMCC41LIB=C:\Program Files\Keil\ARM\RV31\LIB
SET CPU_TYPE=STM32F103C8
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x00000000
"C:\Program Files\Keil\ARM\BIN40\ArmAsm" --Via "stm32f10x._ia"
"C:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "tsliic_rev_a.__i"
